#!/bin/bash

# Prints out battery percentage

get_battery()
{
	local CHARGING_ICON=' '
	local WARNING_ICON=' '
	local BATTERY_FULL_ICON=''
	local BATTERY_2_ICON=''
	local BATTERY_3_ICON=''
	local BATTERY_4_ICON=''

	local FULL_AT=98

	local BAT_ICON=""
	local ICON=""
	# The vast majority of people only use one battery.

	if [ -d /sys/class/power_supply/BAT0 ]; then
		capacity=$(cat /sys/class/power_supply/BAT0/capacity)
		charging=$(cat /sys/class/power_supply/BAT0/status)
		if [[ "$charging" == "Charging" ]]; then
			ICON="$CHARGING_ICON"
		elif [[ $capacity -le 25 ]]; then
			ICON="$WARNING_ICON"
		fi

		if [[ $capacity -ge $FULL_AT ]]; then
			BAT_ICON=$BATTERY_FULL_ICON
		elif [[ $capacity -le 25 ]]; then
			BAT_ICON=$BATTERY_4_ICON
		elif [[ $capacity -le 60 ]]; then
			BAT_ICON=$BATTERY_3_ICON
		elif [[ $capacity -le $FULL_AT ]]; then
			BAT_ICON=$BATTERY_2_ICON
		fi
	fi
	if [ "$(ls /sys/class/power_supply | grep BAT0)" != "" ]; then
		echo "$ICON$BAT_ICON $capacity%"
	fi
}

get_battery
